export const GET_LEAGUES = 'GET_LEAGUES';
export const GET_LEAGUES_SUCCESS = 'GET_LEAGUES_SUCCESS';
export const GET_LEAGUES_ERROR = 'GET_LEAGUES_ERROR';

export const GET_LEAGUE_DETAILS = 'GET_LEAGUE_DETAILS';
export const GET_LEAGUE_DETAILS_SUCCESS = 'GET_LEAGUE_DETAILS_SUCCESS';
export const GET_LEAGUE_DETAILS_ERROR = 'GET_LEAGUE_DETAILS_ERROR';

export const CREATE_LEAGUE = 'CREATE_LEAGUE';
export const CREATE_LEAGUE_SUCCESS = 'CREATE_LEAGUE_SUCCESS';
export const CREATE_LEAGUE_ERROR = 'CREATE_LEAGUE_ERROR';
export const CLEAR_NEW_LEAGUE_CREATED = 'CLEAR_NEW_LEAGUE_CREATED';

export const JOIN_LEAGUE = 'JOIN_LEAGUE';
export const JOIN_LEAGUE_SUCCESS = 'JOIN_LEAGUE_SUCCESS';
export const JOIN_LEAGUE_ERROR = 'JOIN_LEAGUE_ERROR';
export const CLEAR_NEW_LEAGUE_JOINED = 'CLEAR_NEW_LEAGUE_JOINED';

export const SUBMIT_PICKS = 'SUBMIT_PICKS';
export const SUBMIT_PICKS_SUCCESS = 'SUBMIT_PICKS_SUCCESS';
export const SUBMIT_PICKS_ERROR = 'SUBMIT_PICKS_ERROR';

export const GET_RACE_SCORES = 'GET_RACE_SCORES';
export const GET_RACE_SCORES_SUCCESS = 'GET_RACE_SCORES_SUCCESS';
export const GET_RACE_SCORES_ERROR = 'GET_RACE_SCORES_ERROR';

export const GET_RACES = 'GET_RACES';
export const GET_RACES_SUCCESS = 'GET_RACES_SUCCESS';
export const GET_RACES_ERROR = 'GET_RACES_ERROR';
