version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "f1pickem"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-x8wpzusjymdw"
s3_prefix = "f1pickem"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []