AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  GetLeaguesLambda:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: get-leagues.out
      Timeout: 10
      Events:
        Handler:
          Type: Api
          Properties:
            Path: '/leagues'
            Method: GET

  SubmitPicksLambda:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: submit-picks.out
      Timeout: 10
      Events:
        Handler:
          Type: Api
          Properties:
            Path: '/picks'
            Method: POST
  
  FetchRaceResultsLambda:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: fetch-race-results.out
      Timeout: 10
      Events:
        Handler:
          Type: Api
          Properties:
            Path: '/race-results/{season}/{race_number}'
            Method: GET
  
  GetRaceScoresLambda:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: get-race-scores.out
      Timeout: 10
      Events:
        Handler:
          Type: Api
          Properties:
            Path: '/race-scores/{league}/{race_id}'
            Method: GET

  GetRacesLambda:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: get-races.out
      Timeout: 30
      Events:
        Handler:
          Type: Api
          Properties:
            Path: '/races/{season}'
            Method: GET

  CreateLeagueLambda:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: create-league.out
      Timeout: 30
      Events:
        Handler:
          Type: Api
          Properties:
            Path: '/leagues'
            Method: POST
  
  GetLeagueDetailsLambda:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: get-league-details.out
      Timeout: 30
      Events:
        Handler:
          Type: Api
          Properties:
            Path: '/leagues/{league_id}'
            Method: GET
  
  JoinLeagueLambda:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: join-league.out
      Timeout: 30
      Events:
        Handler:
          Type: Api
          Properties:
            Path: '/leagues/join'
            Method: POST
  
  RefreshLeagueTokenLambda:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: refresh-league-token.out
      Timeout: 30
      Events:
        Handler:
          Type: Api
          Properties:
            Path: '/leagues/{league_id}/token'
            Method: GET

Outputs:
  Endpoint:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"