AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  GetLeaguesLambda:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: get-leagues.out
      Timeout: 10
      Events:
        Handler:
          Type: Api
          Properties:
            Path: '/leagues'
            Method: GET

  SubmitPicksLambda:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: submit-picks.out
      Timeout: 10
      Events:
        Handler:
          Type: Api
          Properties:
            Path: '/picks'
            Method: POST
  
  FetchRaceResultsLambda:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: fetch-race-results.out
      Timeout: 10
      Events:
        Handler:
          Type: Api
          Properties:
            Path: '/race-results/{season}/{race_number}'
            Method: GET
  
  GetRaceScoresLambda:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: get-race-scores.out
      Timeout: 10
      Events:
        Handler:
          Type: Api
          Properties:
            Path: '/race-scores/{league}/{race_id}'
            Method: GET


Outputs:
  Endpoint:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"