AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  Api:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: main
      Timeout: 10
      Events:
        GetLeagues:
          Type: Api
          Properties:
            Path: '/leagues'
            Method: GET

Outputs:
  Endpoint:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"